"""Synthetic bars and provider-shaped payloads for data/facts tests (no network)."""

from __future__ import annotations

import json
from collections.abc import Sequence
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

FIXTURES = Path(__file__).parent / "fixtures"


def fixture(name: str) -> Any:
    path = FIXTURES / name
    return json.loads(path.read_text()) if path.suffix == ".json" else path.read_text()


def day_index(end: date | str, n: int, *, weekdays_only: bool = False) -> pd.DatetimeIndex:
    """n daily bar STARTS (00:00 UTC) ending on `end` inclusive."""
    end_ts = pd.Timestamp(end)
    if end_ts.tzinfo is not None:
        end_ts = end_ts.tz_convert("UTC").tz_localize(None)
    if weekdays_only:
        idx = pd.bdate_range(end=end_ts, periods=n)
    else:
        idx = pd.date_range(end=end_ts, periods=n, freq="D")
    return pd.DatetimeIndex(idx).tz_localize("UTC").rename("start")


def bars_from_closes(closes: Sequence[float] | np.ndarray, index: pd.DatetimeIndex) -> pd.DataFrame:
    """Bars whose open is the previous close and whose range envelopes open and close."""
    c = np.asarray(closes, dtype="float64")
    if len(c) != len(index):
        raise ValueError("closes and index lengths differ")
    o = np.concatenate([[c[0]], c[:-1]])
    return pd.DataFrame(
        {
            "open": o,
            "high": np.maximum(o, c) * 1.002,
            "low": np.minimum(o, c) * 0.998,
            "close": c,
            "volume": np.full(len(c), 1000.0),
        },
        index=index,
    )


def from_log_returns(returns: Sequence[float] | np.ndarray, start: float = 100.0) -> np.ndarray:
    """Closes (len = len(returns) + 1) generated by the given daily log returns."""
    r = np.asarray(returns, dtype="float64")
    return start * np.exp(np.concatenate([[0.0], np.cumsum(r)]))


def alternating(n_returns: int, a: float) -> np.ndarray:
    """+a, -a, +a, ... (zero-mean, |r| = a)."""
    return np.array([a if i % 2 == 0 else -a for i in range(n_returns)])


def random_closes(n: int, *, seed: int, drift: float = 0.0004, vol: float = 0.012) -> np.ndarray:
    rng = np.random.default_rng(seed)
    return from_log_returns(rng.normal(drift, vol, n - 1))


def daily_bars(end: date | str, n: int, *, seed: int, weekdays_only: bool, drift: float = 0.0004,
               vol: float = 0.012) -> pd.DataFrame:
    idx = day_index(end, n, weekdays_only=weekdays_only)
    return bars_from_closes(random_closes(n, seed=seed, drift=drift, vol=vol), idx)


# ---------------------------------------------------------------- provider payload shapes
def binance_payload(bars: pd.DataFrame, interval_ms: int = 86_400_000) -> list[list[Any]]:
    rows = []
    for ts, row in bars.iterrows():
        open_ms = int(pd.Timestamp(ts).timestamp() * 1000)
        rows.append([
            open_ms, f"{row.open:.8f}", f"{row.high:.8f}", f"{row.low:.8f}", f"{row.close:.8f}",
            f"{row.volume:.8f}", open_ms + interval_ms - 1, "0", 0, "0", "0", "0",
        ])
    return rows


def tiingo_payload(bars: pd.DataFrame) -> list[dict[str, Any]]:
    return [
        {
            "date": pd.Timestamp(ts).strftime("%Y-%m-%dT00:00:00.000Z"),
            "open": row.open, "high": row.high, "low": row.low, "close": row.close,
            "volume": row.volume, "adjOpen": row.open, "adjHigh": row.high, "adjLow": row.low,
            "adjClose": row.close, "adjVolume": row.volume, "divCash": 0.0, "splitFactor": 1.0,
        }
        for ts, row in bars.iterrows()
    ]


def utc(*args: int) -> datetime:
    return datetime(*args, tzinfo=UTC)


def universe_history(policy: Any, end: date | str, n: int = 460, *, seed: int = 7) -> dict[str, pd.DataFrame]:
    """Daily signal bars for every universe line ending on `end` (weekdays for Tiingo signals)."""
    out = {}
    for i, line in enumerate(policy.universe.lines):
        weekdays = line.signal.source == "tiingo"
        out[line.symbol] = daily_bars(end, n, seed=seed + i, weekdays_only=weekdays)
    return out
